language: node_js
sudo: required
services:
  - docker

scripts:
  - docker build -t dipeshgod/lms-frontend ./frontend
  - docker build -t dipeshgod/lms-nginx ./nginx
  - docker build -t dipeshgod/lms-backend ./backend
    #  Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

after_success:
  - docker push dipeshgod/lms-frontend
  - docker push dipeshgod/lms-nginx
  - docker push dipeshgod/lms-backend

deploy:
  provider: elasticbeanstalk
  region: 'ap-south-1'
  app: 'learning-management-system'
  env: 'Learningmanagementsystem-env'
  bucket_name: 'elasticbeanstalk-ap-south-1-432756220123'
  bucket_path: 'learning-management-system'
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
